from DataExtract import DataExtraction
from ExcelFormatting import ExcelCreation
import time
import schedule
from flask import Flask, render_template, redirect, url_for, flash, request, jsonify, session
from flask_bootstrap import Bootstrap5
from flask_login import LoginManager, current_user, login_user, logout_user, login_required
from datetime import datetime as dt
from datetime import timedelta
import pytz
from forms import LoginForm, RegisterForm, AddShopForm, GenReportForm, AmendForm, RemoveShopForm, AddItemsForm, \
    AddTypeForm, RemoveItemForm
import os
from werkzeug.security import generate_password_hash, check_password_hash
from DBModels import db, Users, Urls, Shops, ShopLoc, ItemData
from ExportBrain import ExcelExport

from app import app, login_manager

@app.before_request
def refresh_session():
    if current_user.is_authenticated:
        session.permanent = True
        session.modified = True

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/login", methods=["GET", "POST"])
def login_page():
    form = LoginForm()
    if form.validate_on_submit():
        password = form.password.data
        results = db.session.execute(db.select(Users).where(Users.email == form.email.data))
        user = results.scalar()
        if not user:
            flash("That email does not exist, please try again or register.")
            return redirect(url_for("login_page"))
        elif not check_password_hash(user.password, password):
            flash("Incorrect password.")
            return redirect(url_for("login_page"))
        else:
            login_user(user)
            session.permanent = True
            return redirect(url_for("dashboard"))

    return render_template("login.html", form=form)

@app.route("/register", methods=["GET", "POST"])
def register_user():
    form = RegisterForm()
    if form.validate_on_submit():
        result = db.session.execute(db.select(Users).where(Users.email == form.email.data))
        user = result.scalar()

        if user:
            flash("This email is linked to an existing account, please sign in!")
            return redirect(url_for("login_page"))

        #Create password hash:
        hash_and_salted_password = generate_password_hash(
            form.password.data,
            method='pbkdf2:sha256',
            salt_length=8,
        )
        new_user = Users(
            username=form.username.data,
            email=form.email.data,
            password=hash_and_salted_password
        )
        db.session.add(new_user)
        db.session.commit()
        #Authentication of the user with Flask-login:
        login_user(new_user)
        return redirect(url_for("dashboard"))
    return render_template("register.html", form=form, current_user=current_user)

@app.route("/dashboard")
@login_required
def dashboard():
    return render_template("logged-in.html")

@app.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("index"))

#Generated by AI Double Check!
@app.route("/get_shop_name_by_url", methods=["POST"])
@login_required
def get_shop_name_by_url():
    url_id = request.json.get('url_id')
    url_address = request.json.get('url')

    if url_id:
        url_record = db.session.get(Urls, int(url_id))
    # Find the URL in database
    else:
        url_record = db.session.execute(
            db.select(Urls).where(Urls.url_address == url_address)
        ).scalar()

    if url_record:
        # Get the shop associated with this URL
        shop = db.session.execute(
            db.select(Shops).where(Shops.url_id == url_record.id)
        ).scalar()

        if shop:
            return jsonify(shop_name=shop.shop_name)

    return jsonify(shop_name="")

@app.route("/add-shop", methods=["GET", "POST"])
@login_required
def add():
    form = AddShopForm()
    form2 = AddItemsForm()
    form3 = AddTypeForm()

    #Addin population of URL dropdown menu:
    existing_urls = db.session.execute(
        db.select(Urls).where(Urls.user_id == current_user.id)
    ).scalars().all()
    form.url_choice.choices = [(0, '-- Select Existing URL --')] + [(u.id, u.url_address) for u in existing_urls]


    all_locations = db.session.execute(db.select(ShopLoc)
                                       .join(ShopLoc.shops)
                                       .join(Shops.url)
                                       .where(Urls.user_id == current_user.id)).scalars().all()
    form2.shop_loc.choices = [(int(loc.id), loc.shop_loc) for loc in all_locations]

    if request.method == "POST":
        print(f"Form errors: {form.errors}")
        print(f"Form data: url_choice={form.url_choice.data}, shop_url={form.shop_url.data}")
        if form.validate_on_submit():
            print("Form valid.")
            if form.url_choice.data and form.url_choice.data != 0:
                existing_url = db.session.get(Urls, form.url_choice.data)
            else:
                print("Manual Entry triggered. Checking for url existence...")
                entered_url = form.shop_url.data
                existing_url = db.session.execute(db.select(Urls).where(Urls.url_address == entered_url)).scalar()
                if not existing_url:
                    print("Adding URL...")
                    existing_url = Urls(
                        url_address=entered_url,
                        user_id=current_user.id
                    )
                    db.session.add(existing_url)
                    db.session.commit()
                    print("Added URL successfully!")

            # Check if shop Abbr exists for this URL:
            entered_shop = form.shop_name.data
            existing_shop = db.session.execute(
                db.select(Shops).where(
                    Shops.shop_name == entered_shop,
                    Shops.url_id == existing_url.id
                )
            ).scalar()

            # If it doesn't exist for this URL, create it:
            if not existing_shop:
                print("Creating new shop...")
                new_shop_abbr = Shops(
                    shop_name=entered_shop.upper(),
                    url_id=existing_url.id
                )
                db.session.add(new_shop_abbr)
                db.session.commit()
                existing_shop = new_shop_abbr
                print("Shop added successfully!")

            # Finally, check if the location exists within the given shop name abbr:
            entered_loc = form.shop_loc.data
            existing_loc = db.session.execute(
                db.select(ShopLoc).where(
                    ShopLoc.shop_loc == entered_loc,
                    ShopLoc.shop_id == existing_shop.id
                )
            ).scalar()

            if existing_loc:
                flash("This location already exists on record!")
                return redirect(url_for("add"))

            print("adding new location...")
            new_loc = ShopLoc(
                shop_loc=entered_loc,
                shop_id=existing_shop.id,
            )
            db.session.add(new_loc)
            db.session.commit()

            flash(f"New shop information has been added successfully!")
            return redirect(url_for("add"))

        if form2.validate_on_submit():
            #First see if shop location exists in ShopLoc:
            selected_shop = db.session.get(ShopLoc, form2.shop_loc.data)
            date_entered = form2.date.data
            try:
                dt.strptime(date_entered, "%d/%m/%Y")
            except ValueError:
                flash("Please ensure your date format is correct.")

            if selected_shop:
                new_item = ItemData(
                    date=date_entered,
                    shop_name=f"{selected_shop.shop_loc} ({selected_shop.shops.shop_name})",
                    customer=form2.customer.data,
                    description=form2.description.data,
                    product_id=form2.product_id.data,
                    qty=form2.qty.data,
                    price=f"$ {form2.price.data}",
                    subtotal=f"$ {int(form2.qty.data) * int(form2.price.data)}",
                    loc_id=selected_shop.id,
                )
                db.session.add(new_item)
                db.session.commit()

                return redirect(url_for("add"))

    return render_template("add.html", form=form, form2=form2, form3=form3, current_user=current_user)

@app.route("/get_shop_locs/<int:shop_id>")
@login_required
def get_shop_locs(shop_id):
    shop_locs = db.session.execute(
        db.select(ShopLoc).where(ShopLoc.shop_id == shop_id)
    ).scalars().all()
    return jsonify(shop_locs=[{"id": s.id, "name": s.shop_loc} for s in shop_locs])

@app.route("/get_items/<int:loc_id>/<string:date>")
@login_required
def get_items(loc_id, date):
    date_obj = dt.strptime(date, "%Y-%m-%d")
    formatted_date = date_obj.strftime("%d/%m/%Y")
    items = db.session.execute(
        db.select(ItemData).where(
            ItemData.loc_id == loc_id,
            ItemData.date == formatted_date
        )
    ).scalars().all()
    return jsonify(items=[{"id": i.id, "name": f"{i.date} - {i.description} - {i.product_id}"} for i in items])


@app.route("/remove-shop", methods=["GET", "POST"])
@login_required
def remove():
    form = RemoveShopForm()  # Replace with your actual form class name
    form2 = RemoveItemForm()

#------------ FORM 1 CHOICES ------------#

    # 1. Populate URL choices (Always needed for the dropdown to show anything)
    urls = db.session.execute(
        db.select(Urls).where(Urls.user_id == current_user.id)
    ).scalars().all()
    form.url.choices = [(u.id, u.url_address) for u in urls]

    first_url = urls[0] if urls else None

    # Pre-populate all shops to pass validation on POST
    all_locations = db.session.execute(db.select(ShopLoc)
                                   .join(ShopLoc.shops)
                                   .join(Shops.url)
                                   .where(Urls.user_id == current_user.id)
                                       ).scalars().all()
    form.curr_loc.choices = [(s.id, s.shop_loc) for s in all_locations]

    # 2. Handle the "Initial" Shop choices for GET requests
    # We pick the first URL's shops so the second dropdown isn't empty on page load
    if request.method == "GET" and first_url:
        first_loc = db.session.execute(
            db.select(ShopLoc)
            .join(ShopLoc.shops).where(Shops.url_id == first_url.id)
        ).scalars().all()
        form.curr_loc.choices = [(s.id, s.shop_loc) for s in first_loc]

    #--- Auto-fill All shops for Form 2 ---#

    all_shops = db.session.execute(
        db.select(Shops)
        .join(Shops.url)
        .where(Urls.user_id == current_user.id)
    ).scalars().all()
    form2.shop_abbr.choices = [(s.id, s.shop_name) for s in all_shops]

    #--- Auto-fill Shop Locations with all for Post Validation --#
    form2.shop_location.choices = [(l.id, l.shop_loc) for l in all_locations]

    # NOW on GET we sort locations based on shop name #
    if request.method == "GET" and all_shops:
        first_shop_loc = db.session.execute(
            db.select(ShopLoc).where(ShopLoc.shop_id == all_shops[0].id)
        ).scalars().all()
        form2.shop_location.choices = [(s.id, s.shop_loc) for s in first_shop_loc]

    #--- Item_field choices, again all for post validation ---#
    all_items = db.session.execute(
        db.select(ItemData)
        .join(ItemData.shop)
        .join(ShopLoc.shops)
        .join(Shops.url)
        .where(Urls.user_id == current_user.id)
    ).scalars().all()
    form2.item_field.choices = [(i.id, f"{i.date} - {i.shop_name} - {i.customer} - {i.product_id}") for i in all_items]

    #--- Use form flag to see which form was submitted ---#
    form_type = request.form.get("form_type")

    #--- Form 1 Functionality ---#
    if form_type == "remove_url_shop" and form.validate_on_submit():
        if form.url_check.data and form.shop_check.data:
            flash("You can only make one selection, as deleting the URL would delete ALL shop data located within it.")
            return redirect(url_for("remove"))

        #Deleting URL logic:
        if form.url_check.data:
            # Using the session.get() method, because "form.url.data" is an ID
            selected_url = db.session.get(Urls, form.url.data)
            if selected_url:
                db.session.delete(selected_url)
                db.session.commit()
                flash("URL and corresponding shop data removed successfully!")
            else:
                flash("Error: URL not found.")

        #Deleting shop logic:
        elif form.shop_check.data:
            # Again, "form.curr_shop.data" is an ID so we use session.get():
            selected_shop = db.session.get(ShopLoc, form.curr_loc.data)
            if selected_shop:
                db.session.delete(selected_shop)
                db.session.commit()
                flash("The specified shop was removed successfully!")
            else:
                flash("Error: Shop not found.")

        return redirect(url_for("remove"))

    #--- Form 2 Functionality ---#
    if form_type == "remove_item" and form2.validate_on_submit():
        loc_id = form2.shop_location.data
        date_input = dt.strptime(str(form2.date.data), "%Y-%m-%d").strftime("%d/%m/%Y")
        item_id = form2.item_field.data

        selected_item = db.session.execute(
            db.select(ItemData).where(
                ItemData.id == item_id,
                ItemData.loc_id == loc_id,
                ItemData.date == date_input
            )
        ).scalar_one_or_none()

        if selected_item:
            db.session.delete(selected_item)
            db.session.commit()
            flash(f"'{selected_item.description}' has been removed successfully!")
        else:
            flash("Error: Item not found. It may already have been removed!")

        return redirect(url_for("remove"))

    return render_template("remove.html", form=form,form2=form2, current_user=current_user)

#Data in database is sent to the JavaScript in your amend.html with this route:
@app.route("/get_shops/<url_id>")
@login_required
def get_shops(url_id):

    url_record = db.session.get(Urls, url_id)

    if not url_record or url_record.user_id != current_user.id:
        return jsonify(shops=[]), 403


    # Format the data into a list of dictionaries:
    location_list = [{"id": loc.id, "name": loc.shop_loc} for loc in url_record.shop_name.loc]

    # Return it as JSON:
    return jsonify(shops=location_list)

@app.route("/amend", methods=["GET", "POST"]) #Remember your GET and POST methods!
@login_required
def amend():
    form = AmendForm()
    # Code added to inform the "AmendForm" SelectorField that the choices variable needs to be filled with the URLs in database:

    #1.) Fetch all URLs from database and populate "choices" variable:
    #(" .id" is the value, " .url_address" is what the user will see)
    all_urls = db.session.execute(db.select(Urls).where(Urls.user_id == current_user.id)).scalars().all()
    form.shop_url.choices = [(u.id, u.url_address) for u in all_urls]

    #2.) Populate initial shop "choices" (optional, but helps prevent validation errors)
    # If the user has already picked a URL, then show the shops for chosen URL.
    # Otherwise, show an empty list or a "Select URL first" notice message.
    form.curr_loc.choices = [(s.id, s.shop_loc) for s in db.session.execute(
        db.select(ShopLoc).join(ShopLoc.shops)
                        .join(Shops.url)
                        .where(Urls.user_id == current_user.id
                                          )).scalars().all()]

    if form.validate_on_submit():
        url_on_record = db.session.get(Urls, form.shop_url.data)
        loc_on_record = db.session.get(ShopLoc, form.curr_loc.data)

        #Create a boolean to ensure no errors:
        changes_made = True

        #This does two checks - 1) Checks if the field is empty (user didn't want changes made) and 2) if populated,
        #do the changes not match what is on record. If both are met then changes_made will equal to True.
        if form.new_url.data and form.new_url.data != url_on_record.url_address:
            url_on_record.url = form.new_url.data
            changes_made = False

        #Doing the same for the shop names as well:
        if form.new_loc.data and form.new_loc.data != loc_on_record.shop_loc:
            loc_on_record.shop_loc = form.new_loc.data
            changes_made = False

        if not changes_made:
            db.session.commit()
            flash("Amendments saved successfully!")
        else:
            flash("No changes detected, please check your changes and try again.")

    return render_template("amend.html", form=form, current_user=current_user)

# All of this route was AI generated - review and ensure functionality
@app.route('/get-locations/<shop_id>')
def get_locations(shop_id):
    if shop_id == 'all':
        # Return all locations from all shops
        locations = ShopLoc.query.all()
        locations_list = [('all', 'All Locations')] + [(str(loc.id), f"{loc.shop_loc} ({loc.shops.shop_name})") for loc
                                                       in locations]
    else:
        # Return locations for specific shop
        locations = ShopLoc.query.filter_by(shop_id=int(shop_id)).all()
        locations_list = [('all', 'All Locations')] + [(str(loc.id), loc.shop_loc) for loc in locations]

    return jsonify(locations_list)

@app.route("/report", methods=["GET", "POST"])
@login_required
def reports():
    form = GenReportForm()

    #First populate the shops dropdown menu:
    shops = Shops.query.all()
    ## If no choice is made, then the 'all' and "All shops" informs the user that all shops would be queried.
    form.shops.choices = [('all', 'All Shops')] + [(str(shop.id), shop.shop_name) for shop in shops]

    # We need to populate the loc_shop dropdown on both GET and POST requests. (Had to fix AI mistake here)
    if request.method == "POST":
        shop_selected = request.form.get('shops')

        #This shows all locations available for all the shops.
        if shop_selected == 'all':
            all_locations = ShopLoc.query.all()
            form.shop_loc.choices = [('all', 'All Locations')] + [(str(loc.id), f"{loc.shop_loc} ({loc.shops.shop_name})") for loc in all_locations]
        # This is for when a specific shop location is chosen to correctly adjust the original page load choice
        else:
            locations = ShopLoc.query.filter_by(shop_id=int(shop_selected)).all()
            form.shop_loc.choices = [('all', 'All Locations')] + [(str(loc.id), loc.shop_loc) for loc in locations]

    # On a get request the choices stays "all"
    else:
        form.shop_loc.choices = [('all', 'All Locations')]

    if form.validate_on_submit():
        selected_shop = form.shops.data
        selected_shop_loc = form.shop_loc.data
        # print(selected_shop, selected_shop_loc)

        # If custom_date = True collect dates:
        if form.custom_date.data:
            date_from = form.from_date.data
            date_to = form.to_date.data
            from_obj = dt.strptime(date_from, '%Y-%m-%d')
            to_obj = dt.strptime(date_to, '%Y-%m-%d')

        # Else calculate chosen period date:
        else:
            days = int(form.set_period.data)
            to_obj = dt.now()
            from_obj = to_obj - timedelta(days=days)

            date_from = from_obj.strftime('%Y-%m-%d')
            date_to = to_obj.strftime('%Y-%m-%d')
        # Build the query of ItemDate based on the selections
        query = ItemData.query

        # Create and 'if' for if the shop is not the default "all"
        if selected_shop != 'all':
            shop_locations = ShopLoc.query.filter_by(shop_id=int(selected_shop)).all()
            location_ids = [loc.id for loc in shop_locations]
            query = query.filter(ItemData.loc_id.in_(location_ids))

        # Now an 'if' for the location
        if selected_shop_loc != 'all':
            query = query.filter_by(loc_id=int(selected_shop_loc))

        #First we need to Parse the dates (Again, had to fix AI's mistake)
        # from_obj = dt.strptime(date_from, '%Y-%m-%d')
        formated_from = from_obj.strftime("%d/%m/%Y")
        # to_obj = dt.strptime(date_to, '%Y-%m-%d')
        formated_to = to_obj.strftime("%d/%m/%Y")

        # Now, we will filter the date range
        query = query.filter(
            ItemData.date.between(
                formated_from,
                formated_to
            )
        )

        results = query.all()

        if results:

            for p in results:
                p.price = float(p.price.strip("$ ").strip("-"))



            total_items = len(results)
            total_qty = sum(item.qty for item in results)
            total_revenue = [float(i.strip("$ ").strip("-")) for i in (item.subtotal for item in results)]
            total_revenue = sum(total_revenue)

            for sub in results:
                sub.subtotal = float(sub.subtotal.strip("$ ").strip("-"))

            from flask import session
            session["report_data"] = {
                'shop_id': selected_shop,
                "loc_id": selected_shop_loc,
                'date_from': formated_from,
                'date_to': formated_to,
            }

            return render_template("reports.html",
                                   results=results,
                                   total_items=total_items,
                                   total_qty=total_qty,
                                   total_revenue=total_revenue,
                                   date_from=formated_from,
                                   date_to=formated_to,
                                   form=form,
                                   )

    return render_template("reports.html", form=form, current_user=current_user)

@app.route("/export-excel")
def export_excel():
    exports = ExcelExport(report_data=session.get("report_data"))
    return exports.export_excel()

@app.route("/export-pdf")
def export_pdf():
    exports = ExcelExport(report_data=session.get("report_data"))
    return exports.export_pdf()

EMAIL = os.environ.get('SYSTEM_EMAIL')
PASSWORD = os.environ.get('SYSTEM_PASSWORD')
ALL_DATA = []
TOTAL_SALES = []
EMPTY_STORES = []
SALES_SHOPS = []


def task():

    with app.app_context():
        try:
            hk_tz = pytz.timezone('Asia/Hong_Kong')
            hk_time = dt.now(hk_tz)
            cutoff = hk_time.replace(hour=22, minute=00, second=0, microsecond=0)

            get_data = DataExtraction()
            excel = ExcelCreation()

            # Extract the list of existing URLs currently in the database:
            url_list = db.session.execute(db.select(Urls.url_address)).scalars().all()

            for url in url_list:
                get_data.get_website(url)
                # Obtain the url instance from Urls database:
                current_url = db.session.execute(db.select(Urls).where(Urls.url_address == url)).scalar()

                # Getr the current shop abbr to append to the shop_loc name to add to the database for later use:
                current_name_item = db.session.execute(db.select(Shops).where(Shops.url_id == current_url.id)).scalar()
                current_abbr = current_name_item.shop_name

                for loc in db.session.execute(db.select(ShopLoc).where(ShopLoc.shop_id == current_url.id)).scalars().all():
                    # print(shop.shop_name)
                    shop_loc = loc.shop_loc
                    added_abbr =f"{shop_loc} ({current_abbr})"
                    current_data = get_data.open_shops(added_abbr)
                    if len(current_data) == 0:
                        EMPTY_STORES.append(added_abbr)
                    else:
                        SALES_SHOPS.append(added_abbr)
                        for item in current_data:
                            ALL_DATA.append(item)
                get_data.log_out()
                time.sleep(2)

            dict_data = get_data.create_dict(ALL_DATA)
            for sub in range(0, len(dict_data)):
                TOTAL_SALES.append(float(dict_data[f"{sub}"]["Sub."].split(" ")[1]))
            # print(type(TOTAL_SALES))
            form_data = excel.create_excelsheet(dict_data)
            form_populated = True

            if form_data.empty:
                form_populated = False
                remove_columns = []
            else:
                remove_columns = excel.removing_columns(form_data)
                excel.create_pdf(form_data)

            excel.send_mail(email=EMAIL, password=PASSWORD, empty_shop_list=EMPTY_STORES, sales_shops_list=SALES_SHOPS, total=sum(TOTAL_SALES), r_data=remove_columns, send_condition=form_populated)

            if hk_time >= cutoff:
                for num in range(len(dict_data)):
                    """NOTE - The column id 'Shop Name' is actually the location. It is done this way as the system where the
                     data is being collected from has placed it in this way."""
                    try:
                        item = dict_data[f"{num}"]
                        # This way of splitting handles edge cases:
                        shop_name = item["Shop name"].split(" ")
                        if len(shop_name) < 2:
                            item_pop_error = f"Invalid Shop Name. Shop Name: {shop_name}"
                            print(item_pop_error)
                            continue

                        current_loc = shop_name[0]
                        current_abbr = shop_name[1].replace("(", "").replace(")", "")

                        #First find the shop abbr:
                        get_shop_abbr = db.session.execute(
                            db.select(Shops).where(Shops.shop_name == current_abbr)
                        ).scalar()

                        if not get_shop_abbr:
                            item_pop_abbr_error = f"The shop abbreviation {current_abbr} does not exist in the database."
                            print(item_pop_abbr_error)
                            continue

                        #Now, get the location:
                        get_loc = db.session.execute(
                            db.select(ShopLoc).where(
                                ShopLoc.shop_loc == current_loc,
                                ShopLoc.shop_id == get_shop_abbr.id
                            )
                        ).scalar()

                        if not get_loc:
                            item_pop_loc_error = f"The shop location {current_loc} does not exist in the database."
                            print(item_pop_loc_error)
                            continue

                        existing_item = db.session.execute(
                            db.select(ItemData).where(
                                ItemData.date == dict_data[f"{num}"]["Date"],
                                ItemData.product_id == dict_data[f"{num}"]["Product ID"],
                                ItemData.customer == dict_data[f"{num}"]["Customer"],
                            )
                        ).scalar_one_or_none()

                        if not existing_item:
                            new_item = ItemData(
                                date=dict_data[f"{num}"]["Date"],
                                shop_name=dict_data[f"{num}"]["Shop name"],
                                customer=dict_data[f"{num}"]["Customer"],
                                description=dict_data[f"{num}"]["Description"],
                                product_id=dict_data[f"{num}"]["Product ID"],
                                qty=dict_data[f"{num}"]["Qty"],
                                price=dict_data[f"{num}"]["Price"],
                                subtotal=dict_data[f"{num}"]["Sub."],
                                loc_id=get_loc.id,
                            )
                            db.session.add(new_item)

                    except Exception as e:
                        item_pop_general_error = f"Error processing item {num}: {e}"
                        print(item_pop_general_error)
                        continue


                db.session.commit()

        except Exception as e:
            automation_error = f"Error processing automation: {e}"

        finally:
            EMPTY_STORES.clear()
            SALES_SHOPS.clear()
            ALL_DATA.clear()
            TOTAL_SALES.clear()
            try:
                get_data.quit()
            except:
                pass



# schedule.every().day.at("20:52").do(task)
# schedule.every().day.at("22:22").do(task)
#
# import threading
#
# def run_schedule():
#     while True:
#         # task()
#         schedule.run_pending()
#         time.sleep(5)
#
# scheduler_thread = threading.Thread(target=run_schedule, daemon=True)
# scheduler_thread.start()

if __name__ == "__main__":
    app.run(debug=True, use_reloader=False)
